name: Integration tests

on:
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker-compose build --parallel
      - name: Run tests
        run: |
          docker-compose up -d
          sleep 20
          ./test.sh
      - name: Dunp logs
        if: always()
        run: |
          bash dump-logs.sh